// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'libandroid-arm.so': '9b939b72be03d19b813d470d9b68d3e1',
  'libandroid-arm64.so': '6cfd38f0d7fcd17e20a71596aa5995ed',
  'libandroid-x64.so': '1257b6af4d134d980d76629bc4c38a36',
  'libios-arm64.dylib': 'd82e611f1432a802067cde5501e09111',
  'libios-x64.dylib': '270613147446f6c758960451587c90d0',
  'liblinux-arm64.so': '4b5ba6b64a379fa651ca9464f06927aa',
  'liblinux-x64.so': 'd00ac0cb57a6205dd5de1a6130890a8f',
  'libmacos-arm64.dylib': 'd783f4e1c2b0aa41a91be59a8ece1b4a',
  'libmacos-x64.dylib': 'fe4f2b0541115a6bf20b8913e4689895',
  'windows-arm64.dll': 'a6154427c61637a71059a9065f05c08c',
  'windows-x64.dll': 'a090661b4d31d88c534ef0e2c3a24659',
};
