// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'pixer_windows_arm64.dll': '9b0dad9ff15934175829d7fdfe02d906',
  'pixer_windows_x86_64.dll': 'ba8c672b719913858e12c7747bd1a8df',
  'libpixer_android_arm64.so': 'e81c42b3cb730b39bb46ef0bab44e5d1',
  'libpixer_android_armv7.so': '80f3a8185803c1df61bd1e85ca562f2e',
  'libpixer_android_x86_64.so': '1fbbed85ed6ea326701e21a6a3c76f4a',
  'libpixer_ios_arm64.dylib': 'de583977f5c6a743840b26497a14c440',
  'libpixer_ios_sim_arm64.dylib': 'b36f167ab523a6d193014cf8c84c9d8c',
  'libpixer_ios_sim_x86_64.dylib': '7e1fbad4aa34c4d1c3bce1243edeb4a0',
  'libpixer_linux_aarch64.so': '66587601f8fcbf91a5d955bfa5eb0ec1',
  'libpixer_linux_x86_64.so': '34b0b65ccdb1af2e670d35923e75bee4',
  'libpixer_macos_arm64.dylib': '4910f035af4f27de63c4cc1084bb9191',
  'libpixer_macos_x86_64.dylib': 'ac8cd9f5c492ceb669fbdaa7054c3aff',
};
