name: fast_image_workspace
description: A workspace for the fast_image package.

environment:
  sdk: ^3.11.0-36.0.dev

workspace:
  - fast_image
  - benchmarks
  - upscale_flutter

hooks:
  user_defines:
    fast_image:
      local_build: true
